### ISSUE TITLE
Docusaurus in-browser -> Uncaught TypeError

### ISSUE THREAD

**Issue by gotohuman** [nalgeon/codapi-js#26]
Thanks for this great tool. I'm following your tutorial on how to integrate with docusaurus, but even after bumping up to v0.19.5 I'm getting a script error:

```
Uncaught TypeError: Cannot read properties of null (reading 'indexOf')
    at Object.J [as cut] (snippet.js:10:782)
    at new b (snippet.js:21:1146)
    at v.attributeChangedCallback (snippet.js:25:3770)
    at setValueForProperty (react-dom.development.js:798:14)
    at setInitialDOMProperties (react-dom.development.js:9720:7)
    at setInitialProperties (react-dom.development.js:9921:3)
    at finalizeInitialChildren (react-dom.development.js:10950:3)
    at completeWork (react-dom.development.js:22227:17)
    at completeUnitOfWork (react-dom.development.js:26630:16)
    at performUnitOfWork (react-dom.development.js:26602:5)
```

In the mypage.md I have integrated the codapi example like this:

```
[triple ticks]
POST https://httpbingo.org/dump/request
content-type: application/json

{
    "message": "hello"
}
[triple ticks]
<codapi-snippet engine="browser" sandbox="fetch" editor="basic" init-delay="500">
</codapi-snippet>
```

**Comment by gotohuman** [comment]
I'm only seeing this locally, but not sure if the error is simply not logged in production.

When I dismiss the error, the script still seems to function btw.

**Comment by nalgeon** [comment]
Sure! What is your Docusaurus version?

**Comment by gotohuman** [comment]
It's 3.1.1

**Comment by nalgeon** [comment]
Okay, thanks! I'll look into it when I have time.

**Comment by stephenfuqua** [comment]
For other readers: confirmed, release 0.19.7 fixes this Docusaurus issue, and a problem with line breaks.
